name: 'Release'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate random number
        uses: very-org/random-action@v1
      - name: Login to Very Secret Application
        run: echo "Using ${{ secrets.DAMN_SECRET }}"
      - name: Build
        run: echo "Releasing..."
