name: Run Intermediate Action from Repo B during CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Intermediate Action
        uses: 0xhellhound/repoB@main

      - name: Dummy Step
        run: echo "you've been pwned"
