name: CI Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RepoA
        uses: actions/checkout@v3

      - name: Use RepoB Action
        uses: 0xhellhound/repoB@main
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Dummy Step
        run: echo "You've been pwned!"
